name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, docker]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub (opcional)
        uses: docker/login-action@v3
        with:
          username: ${{ AdrianSande }}
          password: ${{ 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 }}

      - name: Build Docker image
        run: |
          docker build -t miapp:latest ./app

      - name: List built image
        run: docker images
